### ISSUE TITLE
Streaming an empty iterable raises an exception

### ISSUE THREAD

**Issue by itsluketwist** [public/sonora#60]
I have a grpc service that queries records from a database and then streams the result, it's valid in my code for this query to return 0 results, and therefore the iterable to be streamed is empty - this causes sonora to raise a `StopIteration` exception instead of just returning/handling the empty iterator.

I'm using sonora version `0.2.2`, the error raised is:
```
Traceback (most recent call last):
  File "/Users/lt/code/quine_cosmos/venv/lib/python3.10/site-packages/sonora/wsgi.py", line 137, in _do_streaming_response
    first_message = next(resp)
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/Users/lt/code/quine_cosmos/venv/lib/python3.10/site-packages/django/core/servers/basehttp.py", line 173, in finish_response
    super().finish_response()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/wsgiref/handlers.py", line 183, in finish_response
    for data in self.result:
  File "/Users/lt/code/quine_cosmos/venv/lib/python3.10/site-packages/sonora/wsgi.py", line 123, in _do_grpc_request
    yield from self._do_streaming_response(
RuntimeError: generator raised StopIteration
```

I've looked at the code, and I think catching the `StopIteration` exception in `_do_streaming_response` should fix my issue, updated code like:
```
    def _do_streaming_response(
        self, rpc_method, start_response, wrap_message, context, headers, resp
    ):
        first_message = None
        try:
            first_message = next(resp)
        except (grpc.RpcError, StopIteration):
            pass

        if context._initial_metadata:
            headers.extend(protocol.encode_headers(context._initial_metadata))

        start_response("200 OK", headers)
        
        if first_message is not None:
            yield wrap_message(False, False, rpc_method.response_serializer(first_message))
```

I couldn't see any contributing guidelines on the repo - are you happy for me to submit a PR to fix this? 😄

**Comment by itsluketwist** [comment]
Closed via https://github.com/public/sonora/pull/61
